enum GenresEnum{
  action,
  adventure,
  animation,
  comedy,
  crime,
  disaster,
  documentary,
  drama,
  eastern,
  family,
  fanFilm,
  fantasy,
  filmNoir,
  history,
  holiday,
  horror,
  indie,
  music,
  mystery,
  none,
  road,
  romance,
  scienceFiction,
  short,
  sports,
  sportingEvent,
  suspense,
  thriller,
  tvMovie,
  war,
  western,
}

Map<GenresEnum, String> genresEnumPtDescription = {
  GenresEnum.action: "Ação",
  GenresEnum.adventure: "Aventura",
  GenresEnum.animation: "Animação",
  GenresEnum.comedy: "Comédia",
  GenresEnum.crime: "Crime",
  GenresEnum.disaster: "Desastre",
  GenresEnum.documentary: "Documentário",
  GenresEnum.drama: "Drama",
  GenresEnum.eastern: "Oriental",
  GenresEnum.family: "Família",
  GenresEnum.fanFilm: "Filme de fã",
  GenresEnum.fantasy: "Fantasia",
  GenresEnum.filmNoir: "Pessimista",
  GenresEnum.history: "História",
  GenresEnum.holiday: "Ferido",
  GenresEnum.horror: "Terror",
  GenresEnum.indie: "Indie",
  GenresEnum.music: "Musical",
  GenresEnum.mystery: "Mistéro",
  GenresEnum.none: "Nenhum",
  GenresEnum.road: "Estrada",
  GenresEnum.romance: "Romance",
  GenresEnum.scienceFiction: "Ficção científica",
  GenresEnum.short: "Curto",
  GenresEnum.sports: "Esportes",
  GenresEnum.sportingEvent: "Evento esportivo",
  GenresEnum.suspense: "Suspense",
  GenresEnum.thriller: "Suspense",
  GenresEnum.tvMovie: "Filme de TV",
  GenresEnum.war: "Guerra",
  GenresEnum.western: "Ocidental",
};

Map<GenresEnum, String> genresEnumValue = {
  GenresEnum.action: "action",
  GenresEnum.adventure: "adventure",
  GenresEnum.animation: "animation",
  GenresEnum.comedy: "comedy",
  GenresEnum.crime: "crime",
  GenresEnum.disaster: "disaster",
  GenresEnum.documentary: "documentary",
  GenresEnum.drama: "drama",
  GenresEnum.eastern: "eastern",
  GenresEnum.family: "family",
  GenresEnum.fanFilm: "fan-film",
  GenresEnum.fantasy: "fantasy",
  GenresEnum.filmNoir: "film-noir",
  GenresEnum.history: "history",
  GenresEnum.holiday: "holiday",
  GenresEnum.horror: "horror",
  GenresEnum.indie: "indie",
  GenresEnum.music: "music",
  GenresEnum.mystery: "mystery",
  GenresEnum.none: "none",
  GenresEnum.road: "road",
  GenresEnum.romance: "romance",
  GenresEnum.scienceFiction: "science-fiction",
  GenresEnum.short: "short",
  GenresEnum.sports: "sports",
  GenresEnum.sportingEvent: "sporting-event",
  GenresEnum.suspense: "suspense",
  GenresEnum.thriller: "thriller",
  GenresEnum.tvMovie: "tv-movie",
  GenresEnum.war: "war",
  GenresEnum.western: "western",
};