name: popcorn_app_mobx
version: 1.0.0+1
description: Popcorn App;
environment: 
  sdk: '>=2.2.2 <3.0.0'

dependencies: 
  cached_network_image: ^1.1.3
  shared_preferences: ^0.5.4+3
  flutter_localizations: 
     sdk: flutter
  flutter_mobx: ^0.3.3+1
  mobx: ^0.3.9+1
  dio: ^3.0.4
  rxdart: ^0.22.6
  bloc_pattern: ^2.5.0
  loading_loading: ^0.1.1
  
  widgets:
    path: D:\gitlab\Flutter\packages\widgets

  flutter: 
    sdk: flutter

scripts:
  build: flutter packages pub run build_runner watch
  mobx: flutter packages pub run build_runner watch --delete-conflicting-outputs

dev_dependencies: 
  mobx_codegen: ^0.3.10
  build_runner: 
  mockito: ^4.1.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true